version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            npm ci
            npm t
      - persist_to_workspace:
          root: .
          paths:
            - index.js
            - package.json
            - package-lock.json
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            npm publish --access public

workflows:
  version: 2
  ci:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
